In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from category_encoders import OrdinalEncoder
from sklearn.svm import SVC
from sklearn.ensemble import BaggingClassifier
from sklearn.datasets import make_classification
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,f1_score,roc_auc_score


from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC


In [2]:
one_hot_encoder=OneHotEncoder()
ordinal_encoder=OrdinalEncoder()
label_encoder=LabelEncoder()

In [3]:
data=pd.read_csv("C:/Users/Yuthayakarthick/Documents/Amal_Docs_Codes/Data_sets/emoji-full-codes-csv-printout - Copy.csv")
data

emojis hex value  decimal discription     class
0        😄     1f604   128516       smile  positive
1        😆     1f606   128518    laughing  positive
2        😊     1f60a   128522       blush  positive
3        😃     1f603   128515      smiley  positive
4        ☺      263a     9786     relaxed  positive
..     ...       ...      ...         ...       ...
176      🌀     1f300   127744     cyclone    nutral
177      🌁     1f301   127745       foggy    nutral
178      🌊     1f30a   127754       ocean    nutral
179      🐱     1f431   128049         cat    nutral
180      🐶     1f436   128054         dog    nutral

[181 rows x 5 columns]

In [4]:

data = data[:181]
data=data.drop(['emojis','discription','hex value'],axis=1)

In [5]:
data.head(5)

decimal     class
0   128516  positive
1   128518  positive
2   128522  positive
3   128515  positive
4     9786  positive

In [6]:
dis=data['class'].value_counts()
print(dis,"\nTotal is",len(dis))

nutral      65
positive    62
negative    54
Name: class, dtype: int64 
Total is 3


In [7]:
data['class']=label_encoder.fit_transform(data['class'])

In [8]:
data

decimal  class
0     128516      2
1     128518      2
2     128522      2
3     128515      2
4       9786      2
..       ...    ...
176   127744      1
177   127745      1
178   127754      1
179   128049      1
180   128054      1

[181 rows x 2 columns]

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 181 entries, 0 to 180
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   decimal  181 non-null    int64
 1   class    181 non-null    int32
dtypes: int32(1), int64(1)
memory usage: 2.2 KB


In [10]:
x=data.drop(['class'],axis=1)
y=data['class']

In [11]:
x_train,x_test,y_train,y_test=train_test_split(x,y)

In [12]:
print(x_train)

     decimal
123   128145
51    128526
131   128118
153   128585
18    128537
..       ...
179   128049
80     10068
148   128569
167   128101
11    128524

[135 rows x 1 columns]


In [13]:
print(y_train)

123    1
51     2
131    1
153    0
18     2
      ..
179    1
80     1
148    2
167    1
11     2
Name: class, Length: 135, dtype: int32


In [53]:
model=RandomForestClassifier(n_estimators=1000,min_samples_split=5,min_samples_leaf=4,max_features='auto',max_depth=100,bootstrap=True)
model.fit(x_train,y_train)
model.score(x_test,y_test)

0.5869565217391305

In [ ]:
'n_estimators': 1000,
 'min_samples_split': 5,
 'min_samples_leaf': 4,
 'max_features': 'auto',
 'max_depth': 100,
 'bootstrap': True

In [21]:
svc.fit(x_train,y_train)
svc.score(x_test,y_test)

0.21739130434782608

In [22]:
lr.fit(x_train,y_train)
lr.score(x_test,y_test)


0.15217391304347827

In [40]:
model.classes_

array([0, 1, 2])

In [16]:
# x_test
# a = np.array([128072,128106])
# a = a.reshape(-1,1)

In [33]:
pred=model.predict(x_test)


In [38]:
print("accuracy:",accuracy_score(pred,y_test)*100)


accuracy: 71.73913043478261


In [19]:
# %pip install xgboost
import xgboost

In [20]:
svc=SVC()
lr=LogisticRegression()

In [29]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=9)
kf

KFold(n_splits=9, random_state=None, shuffle=False)

In [30]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[1 2 3 4 5 6 7 8] [0]
[0 2 3 4 5 6 7 8] [1]
[0 1 3 4 5 6 7 8] [2]
[0 1 2 4 5 6 7 8] [3]
[0 1 2 3 5 6 7 8] [4]
[0 1 2 3 4 6 7 8] [5]
[0 1 2 3 4 5 7 8] [6]
[0 1 2 3 4 5 6 8] [7]
[0 1 2 3 4 5 6 7] [8]


In [ ]:
from sklearn.model_selection import StratifiedKFold
fold=StratifiedKFold(n_splits=4)

In [ ]:
scores_l[]
scoree_svm=[]
score_rf=[]

